namespace Bitprim
{

    public enum ErrorCode
    {
        // general codes
        Success = 0,
        Deprecated = 6,
        Unknown = 43,
        NotFound = 3,
        FileSystem = 42,
        NonStandard = 17,
        NotImplemented = 4,
        Oversubscribed = 71,

        // network
        ServiceStopped = 1,
        OperationFailed = 2,
        ResolveFailed = 7,
        NetworkUnreachable = 8,
        AddressInUse = 9,
        ListenFailed = 10,
        AcceptFailed = 11,
        BadStream = 12,
        ChannelTimeout = 13,
        AddressBlocked = 44,
        ChannelStopped = 45,
        PeerThrottling = 73,

        // database
        StoreBlockDuplicate = 66,
        StoreBlockInvalidHeight = 67,
        StoreBlockMissingParent = 68,

        // blockchain
        DuplicateBlock = 51,
        OrphanBlock = 5,
        InvalidPreviousBlock = 24,
        InsufficientWork = 48,
        OrphanTransaction = 14,
        InsufficientFee = 70,
        DustyTransaction = 76,
        StaleChain = 75,

        // check header
        InvalidProofOfWork = 26,
        FuturisticTimestamp = 27,

        // accept header
        CheckpointsFailed = 35,
        OldVersionBlock = 36,
        IncorrectProofOfWork = 32,
        TimestampTooEarly = 33,

        // check block
        BlockSizeLimit = 50,
        EmptyBlock = 47,
        FirstNotCoinbase = 28,
        ExtraCoinbases = 29,
        InternalDuplicate = 49,
        BlockInternalDoubleSpend = 15,
        MerkleMismatch = 31,
        BlockLegacySigopLimit = 30,

        // accept block
        BlockNonFinal = 34,
        CoinbaseHeightMismatch = 37,
        CoinbaseValueLimit = 41,
        BlockEmbeddedSigopLimit = 52,

        // check transaction
        EmptyTransaction = 20,
        PreviousOutputNull = 23,
        SpendOverflow = 21,
        InvalidCoinbaseScriptSize = 22,
        CoinbaseTransaction = 16,
        TransactionInternalDoubleSpend = 72,
        TransactionSizeLimit = 53,
        TransactionLegacySigopLimit = 54,

        // accept transaction
        TransactionNonFinal = 74,
        PrematureValidation = 69,
        UnspentDuplicate = 38,
        MissingPreviousOutput = 19,
        DoubleSpend = 18,
        CoinbaseMaturity = 46,
        SpendExceedsValue = 40,
        TransactionEmbeddedSigopLimit = 55,
        SequenceLocked = 78,

        // connect input
        InvalidScript = 39,
        InvalidScriptSize = 56,
        InvalidPushDataSize = 57,
        InvalidOperationCount = 58,
        InvalidStackSize = 59,
        InvalidStackScope = 60,
        InvalidScriptEmbed = 61,
        InvalidSignatureEncoding = 62,
        invalidSignatureLaxEncoding = 63,
        IncorrectSignature = 64,
        StackFalse = 65,

        // op eval
        OpDisabled = 100,
        OpReserved,
        OpPushSize,
        OpPushData,
        OpIf,
        OpNotIf,
        OpElse,
        OpEndIf,
        OpVerify1,
        OpVerify2,
        OpReturn,
        OpToAltStack,
        OpFromAltStack,
        OpDrop2,
        OpDup2,
        OpDup3,
        OpOver2,
        OpRot2,
        OpSwap2,
        OpIfDup,
        OpDrop,
        OpDup,
        OpNip,
        OpOver,
        OpPick,
        OpRoll,
        OpRot,
        OpSwap,
        OpTuck,
        OpSize,
        OpEqual,
        OpEqualVerify1,
        OpEqualVerify2,
        OpAdd1,
        OpSub1,
        OpNegate,
        OpAbs,
        OpNot,
        OpNonZero,
        OpAdd,
        OpSub,
        OpBoolAnd,
        OpBoolOr,
        OpNumEqual,
        OpNumEqualVerify1,
        OpNumEqualVerify2,
        OpNumNotEqual,
        OpLessThan,
        OpGreaterThan,
        OpLessThanOrEqual,
        OpGreaterThanOrEqual,
        OpMin,
        OpMax,
        OpWithin,
        OpRipemd160,
        OpSha1,
        OpSha256,
        OpHash160,
        OpHash256,
        OpCodeSeperator,
        OpCheckSigVerify1,
        OpCheckSig,
        OpCheckMultisigVerify1,
        OpCheckMultisigVerify2,
        OpCheckMultisigVerify3,
        OpCheckMultisigVerify4,
        OpCheckMultisigVerify5,
        OpCheckMultisigVerify6,
        OpCheckMultisigVerify7,
        OpCheckMultisig,
        OpCheckLocktimeVerify1,
        OpCheckLocktimeVerify2,
        OpCheckLocktimeVerify3,
        OpCheckLocktimeVerify4,
        OpCheckLocktimeVerify5,
        OpCheckLocktimeVerify6,
        OpCheckSequenceVerify1,
        OpCheckSequenceVerify2,
        OpCheckSequenceVerify3,
        OpCheckSequenceVerify4,
        OpCheckSequenceVerify5,
        OpCheckSequenceVerify6,
        OpCheckSequenceVerify7
    };

}